### ISSUE TITLE
Cannot open the file as archive

### ISSUE THREAD

**Issue by UnrealKaraulov** [reksar/vsget#3]
Getting Windows SDK
- Downloading Windows SDK ISO ... OK
- Extracting SDK Installers ... ERROR: d:\WINSDK\SDK\tmp\sdk.iso
Cannot open the file as archive

**Comment by UnrealKaraulov** [comment]
d:\WINSDK\SDK\tmp\sdk.iso size 345 bytes
```
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>403 - Forbidden</title>
	</head>
	<body>
		<h1>403 - Forbidden</h1>
	</body>
</html>
```

```https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/22621.2428.230929-1800.ni_release_svc_prod1_WindowsSDK.iso``` 403 - Forbidden from BY

ping software-static.download.prss.microsoft.com = sni1gl.wpc.sigmacdn.net [152.199.21.175]

**Comment by UnrealKaraulov** [comment]
@reksar I manually download windows sdk and move it to sdk.iso 

Next I got this error:
```
Getting lessmsi
- Downloading ... FAIL
```

**Comment by reksar** [comment]
@UnrealKaraulov 

I'm guessing your region (BY) is blocked by Microsoft for political reasons and you need to use a VPN/proxy. It's possible to add a proxy option for the vsget downloader, but I'll leave that to you for now.

Without this option, you will need a VPN/proxy for the entire network. You can try some of:
* https://frkn.org/#ru (see about in podcast https://www.youtube.com/watch?v=z8XpHxuWGxc)
* https://reqrypt.org/tallow.html
* https://github.com/xjasonlyu/tun2socks
