### ISSUE TITLE
Feature request: support for x64(host-target)-x86(platforms)

### ISSUE THREAD

**Issue by hellishvictor** [reksar/vsget#5]
Hi, the title says it all, it would be awesome have (for x64 host) x86 platform support!
Cheers.

**Comment by reksar** [comment]
I am unable to maintain this now. But you can use the current x64-x64 as the template for x64-x86.

Below are general steps, not instructions.

First you need to install Visual Studio the normal way.

Create `vsix-uncache\vc-x64-x86.txt` by analogy with the `vsix-uncache\vc-x64-x64.txt`.

Generate `vsix-groups\*.txt` using `vsuncache`. As a result, in addition to `vsix-groups\vc-x64-x64.<your version>.txt`, you should get `vsix-groups\vc-x64-x86.<your version>.txt` file.

Also you need to create the `vs-tools\vcvars-x64-x86.bat` by analogy with `vs-tools\vcvars-x64-x64.bat`.

At this point, you should have the working version of this project that allows you to get the x64-x86 tools. So, if you test it and everything will be OK, then commit changes and send the PR)

How to test? Set the necessary vars the head of the `vsget.bat`:

```bat
rem  MSVC v143
set VC_V=14.33.31629
set VC_GROUP=vc-x64-x64.%VC_V%

rem  MSBuild v170
set MSBUILD_V=17.3.1.2241501
set MSBUILD_GROUP=msbuild-x64.%MSBUILD_V%

rem  Windows SDK v10.0.22621.755
set SDK_URL=https://go.microsoft.com/fwlink/?linkid=2196240

rem  VC Vars for Host x64 and Platform x64
set VCVARS=vcvars-x64-x64
```

Finally use `vsget.bat` and make sure everything is OK.

**Comment by hellishvictor** [comment]
Thank you for the detailed explanation!
